package io.realm.exceptions;
import io.realm.SyncConfiguration;
public class DownloadingRealmInterruptedException extends RuntimeException {
public DownloadingRealmInterruptedException(SyncConfiguration syncConfig, Throwable exception) {
super("Realm was interrupted while downloading the latest changes from the server: " + syncConfig.getPath(),
exception);
}
public DownloadingRealmInterruptedException(SyncConfiguration syncConfig, String message) {
super("Realm was interrupted while downloading the latest changes from the server: " + syncConfig.getPath() + "\n" + message);
}
}
